/**
 * Builds one published page per interface language.
 *
 * index.html is both the markup source and the Spanish page: the script fills
 * every element carrying a data-i18n hook with the translation, rewrites the
 * head block between the i18n:head markers, and writes the other languages to
 * their own directory (/en/). Pre-rendering matters because a crawler must be
 * able to read each language without running the application, and because a
 * link shared from the English page has to preview in English.
 *
 * The data-i18n attributes stay in the output, so the application keeps
 * translating at runtime and running the script twice changes nothing.
 *
 *   node tools/build-pages.mjs
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { DEFAULT_LANGUAGE, LANGUAGES, translator } from '../js/i18n.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Absolute home of the published site: change it if the site moves. */
const SITE = 'https://dibanez.github.io/mecanografia/';

const urlFor = (language) => (language === DEFAULT_LANGUAGE ? SITE : `${SITE}${language}/`);

function escapeHtml(value) {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Head block: title, description, canonical, alternates and link preview. */
function headBlock(language, t) {
  const alternates = LANGUAGES.map(
    ({ id }) => `    <link rel="alternate" hreflang="${id}" href="${urlFor(id)}" />`,
  ).join('\n');
  const otherLocales = LANGUAGES.filter(({ id }) => id !== language)
    .map(({ id }) => `    <meta property="og:locale:alternate" content="${translator(id)('meta.locale')}" />`)
    .join('\n');

  return `    <!-- i18n:head — generated by tools/build-pages.mjs; edit the copy in js/i18n-copy.js -->
    <title>${escapeHtml(t('meta.title'))}</title>
    <meta name="description" content="${escapeHtml(t('meta.description'))}" />
    <link rel="canonical" href="${urlFor(language)}" />
${alternates}
    <link rel="alternate" hreflang="x-default" href="${urlFor(DEFAULT_LANGUAGE)}" />
    <!-- Link preview. Update SITE in tools/build-pages.mjs if the site moves off GitHub Pages. -->
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Mecanografía" />
    <meta property="og:title" content="${escapeHtml(t('meta.title'))}" />
    <meta property="og:description" content="${escapeHtml(t('meta.ogDescription'))}" />
    <meta property="og:url" content="${urlFor(language)}" />
    <meta property="og:image" content="${SITE}og.png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:locale" content="${t('meta.locale')}" />
${otherLocales}
    <meta name="twitter:card" content="summary_large_image" />
    <!-- /i18n:head -->`;
}

/**
 * Fills the three translation hooks. Elements carrying one never nest another
 * of the same tag, which is what lets the closing tag be found by name.
 */
function translateMarkup(html, t) {
  const inner = (attribute) =>
    new RegExp(`<(\\w+)([^>]*\\s${attribute}="([^"]+)"[^>]*)>([\\s\\S]*?)</\\s*\\1\\s*>`, 'g');

  let out = html.replace(inner('data-i18n-html'), (_match, tag, attrs, key) =>
    `<${tag}${attrs}>${t(key)}</${tag}>`,
  );
  out = out.replace(inner('data-i18n'), (_match, tag, attrs, key) =>
    `<${tag}${attrs}>${escapeHtml(t(key))}</${tag}>`,
  );

  // data-i18n-attr carries "attribute:key" pairs to write into the open tag.
  return out.replace(/<(\w+)([^>]*\sdata-i18n-attr="([^"]+)"[^>]*)>/g, (_match, tag, attrs, pairs) => {
    let rewritten = attrs;
    for (const pair of pairs.split(',')) {
      const [attribute, key] = pair.split(':').map((part) => part.trim());
      if (!attribute || !key) continue;
      const value = escapeHtml(t(key)).replace(/"/g, '&quot;');
      const existing = new RegExp(`\\s${attribute}="[^"]*"`);
      rewritten = existing.test(rewritten)
        ? rewritten.replace(existing, ` ${attribute}="${value}"`)
        : `${rewritten} ${attribute}="${value}"`;
    }
    return `<${tag}${rewritten}>`;
  });
}

function buildPage(source, language) {
  const t = translator(language);
  const head = source.replace(
    /    <!-- i18n:head[\s\S]*?<!-- \/i18n:head -->/,
    () => headBlock(language, t),
  );
  const translated = translateMarkup(head, t).replace(
    /<html lang="[^"]*">/,
    `<html lang="${language}">`,
  );

  // Every language but the default lives one directory deeper.
  return language === DEFAULT_LANGUAGE
    ? translated
    : translated.replace(/(href|src)="(css|js)\//g, '$1="../$2/');
}

function sitemap() {
  const entries = LANGUAGES.map(({ id }) => {
    const alternates = [
      ...LANGUAGES.map((other) => [other.id, urlFor(other.id)]),
      ['x-default', urlFor(DEFAULT_LANGUAGE)],
    ]
      .map(([hreflang, href]) => `    <xhtml:link rel="alternate" hreflang="${hreflang}" href="${href}" />`)
      .join('\n');
    return `  <url>\n    <loc>${urlFor(id)}</loc>\n${alternates}\n  </url>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
${entries}
</urlset>
`;
}

async function main() {
  const source = await readFile(join(ROOT, 'index.html'), 'utf8');
  if (!source.includes('<!-- i18n:head')) {
    throw new Error('index.html has no i18n:head block to generate');
  }

  for (const { id } of LANGUAGES) {
    const page = buildPage(source, id);
    const target = id === DEFAULT_LANGUAGE ? join(ROOT, 'index.html') : join(ROOT, id, 'index.html');
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, page);
    console.log(`wrote ${target.replace(ROOT + '/', '')}`);
  }

  await writeFile(join(ROOT, 'sitemap.xml'), sitemap());
  await writeFile(
    join(ROOT, 'robots.txt'),
    `User-agent: *\nAllow: /\n\nSitemap: ${SITE}sitemap.xml\n`,
  );
  console.log('wrote sitemap.xml, robots.txt');
}

await main();
